### ISSUE TITLE
Excluding and including groups for keyword clears page

### ISSUE THREAD

**Issue by colenewcomer** [nyaruka/floweditor#1046] opened 2022-02-22 02:51 UTC
RePro:
-create keyword that excludes “group 1” but includes “group 2”
-add contact to both groups in a flow and then enter the keyword

Expected result: Either exclude or include the message based on intent
Actual result: Cleared screen

Console Error:
<img width="552" alt="Screen Shot 2022-02-21 at 6 49 16 PM" src="https://user-images.githubusercontent.com/96800852/155054053-93622fce-3666-496c-b0ee-24b26ce46fd6.png">

**Comment by ericnewcomer** [comment] 2022-02-23 19:11
Is keyword here a trigger? I tried this, but I'm not able to reproduce this. I think I need clearer steps.

In this example, I have a keyword trigger "grouptest" that includes "another group" and excludes "Missing"

<img width="586" alt="Screen Shot 2022-02-23 at 11 10 17 AM" src="https://user-images.githubusercontent.com/211652/155390371-1bde1520-4323-4dc8-a84f-06e130fc000a.png">

**Comment by colenewcomer** [comment] 2022-02-23 19:32
I mistook the error for a previous bug I submitted, though there is an alternate bug here, depending on how the flow is intended to respond.

**Comment by ericnewcomer** [comment] 2022-02-23 19:36
I believe the exclusion rule here wins, and as such, the trigger is not firing. If I remove the contact from the exclusion group it fires as expected. Closing this as designed.

**Closed by ericnewcomer** 2022-02-23 19:36 UTC
