### ISSUE TITLE
Have an option to copy multiple nodes after selecting them

### ISSUE THREAD

**Issue by mdshamoon** [nyaruka/floweditor#1049] opened 2022-03-04 09:15 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes in a flow we have kind of similar node structure that needs to be copied

**Describe the solution you'd like**
Have an option to select multiple nodes and copy them which are just copied adjacent to the nodes

**Comment by ericnewcomer** [comment] 2022-03-04 18:46
Duplicate of #1017

**Closed by ericnewcomer** 2022-03-04 18:46 UTC
