### ISSUE TITLE
Date comparisons with 0 are failing

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#785] opened 2020-01-15 18:01 UTC
![image](https://user-images.githubusercontent.com/82857/72458783-3fe84f00-3797-11ea-973c-22a9db949024.png)

<img width="804" alt="image" src="https://user-images.githubusercontent.com/82857/72458733-26df9e00-3797-11ea-99d6-f590664d78ad.png">

<img width="359" alt="image" src="https://user-images.githubusercontent.com/82857/72458757-31019c80-3797-11ea-8ca1-7a15aa10ae6b.png">

**Comment by ericnewcomer** [comment] 2020-01-15 18:36
Duplicate of #777

**Closed by ericnewcomer** 2020-01-15 18:36 UTC
