### ISSUE TITLE
Flow JSON becoming invalid by following the mentioned steps

### ISSUE THREAD

**Issue by mdshamoon** [nyaruka/floweditor#1205] opened 2023-11-15 11:51 UTC
**Describe the bug**
The flow JSON becomes invalid when following the below mentioned steps. Might be an edge condition but we are seeing this once in every two months by one of our users.

**To Reproduce**
https://github.com/nyaruka/rapidpro/assets/32592458/07069d7c-4d77-4a3b-bd7f-a18e2f5588da

**Expected behavior**
There should be no errors

**Comment by ericnewcomer** [comment] 2023-11-15 17:10
Just some notes here:

 * Was able to reproduce following the precise steps
 * The flow definition is not saved since it fails validation
 * Refreshing and removing the same node succeeds, so it has something to do with active state during creation using these steps

**Comment by mdshamoon** [comment] 2023-12-23 18:15
@ericnewcomer are you checking this. This seems to happen more frequently now for our clients. 
Let me know if I can raise a PR for the fix.

**Comment by ericnewcomer** [comment] 2023-12-24 23:36
Thanks, I'm on holiday until January 2nd, but will have a look when I'm back!

**Comment by mdshamoon** [comment] 2024-01-02 07:40
Sure thanks. Happy holidays and a great new year.

**Comment by ericnewcomer** [comment] 2024-01-02 23:41
This has been merged and released as of v1.26.1

**Closed by ericnewcomer** 2024-01-02 23:41 UTC
Labels: bug
